# Generated by Django 3.2 on 2021-04-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.FloatField(default=1000.0)),
                ('area', models.CharField(max_length=30)),
                ('bond_year', models.CharField(max_length=10)),
                ('bond_amount', models.FloatField(default=1000.0)),
                ('other_charges', models.FloatField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(default='0.jpeg', upload_to='media')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.landlord')),
            ],
        ),
    ]
