# Generated by Django 3.2 on 2021-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
