# Generated by Django 3.2 on 2021-04-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0003_advert_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
