# Generated by Django 3.2 on 2021-04-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_alter_advert_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='active',
        ),
    ]
