# Generated by Django 3.2 on 2021-04-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_address'),
        ('chat', '0002_auto_20210427_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='advert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='advert',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='adverts.advert'),
        ),
    ]
