# Generated by Django 3.2 on 2021-04-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210427_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
