# Generated by Django 3.2 on 2021-04-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('advert', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.question')),
            ],
        ),
    ]
