# Generated by Django 3.2 on 2021-04-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='advert',
            new_name='query',
        ),
    ]
